### ISSUE TITLE
nagios_nrpe_command is undefined

### ISSUE THREAD

**Issue by kaushalshriyan** [jloh/nagios-nrpe-server#20]
Hi James,

I am encountering the below issue when i try to run 

```
$ ansible-playbook playbooks/nrpe.yml
fatal: [nrpeserver.helpchatdev.in]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'nagios_nrpe_command' is undefined"}
```

```yaml
cat nrpe.yml
  - hosts: nrpeserver
    roles:
     - role: nagios-nrpe-server
    vars:
      nagios_nrpe_server_allowed_hosts:
        - 192.16.214.8
        - 127.0.0.1
```

Any help will be highly appreciable. Thanks in Advance
